version: '3'

services:
  web:
    image: "url-shortener:latest"
    build:
      context: ./app
      dockerfile: backend.dockerfile
    volumes:
      - ./app:/src/
    env_file:
      - .env
    command: [ "sh", "scripts/start-server.sh" ]
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: